### PR TITLE
Exposed JSDocs for web api actions.

### PR DESCRIPTION
**Pull request by electricessence**
This is the first attempt and has been tested using WebStorm as a JSDoc IDE.
It could be expanded much more as well as adding TypeScript defs.

### CODE REVIEW

**Comment by stevegreatrex** [comment]
This looks like a great commit - thanks!

Do you think there are any meaningful tests we can put in place for this?

**Comment by electricessence** [comment]
No it's just jsDocs and the best test is leverage the api by telling 'WebStorm' to load an external library. 
You can simply download the proxy as well and attempt to use it.

**Comment by electricessence** [comment]
Anyone up for auto-generating TypeScript declarations as well :)

**Comment by electricessence** [comment]
BTW... Shameless promotion:
http://electricessence.github.io/TypeScript.NET/

**Pull request merged**
