### PR TITLE
Locking in ProxyHttpHandler.cs #12

### PR DESCRIPTION
**Pull request by swethapavan**
Removed duplicate null check line.

### CODE REVIEW

**Comment by stevegreatrex** [comment]
Hi, thanks for the PR. The reason for checking before acquiring the lock I'd because the act of acquiring the lock can have (admittedly minor, in this case) performance implications. I see no harm in leaving the additional check, unless you think it confuses the purpose of the code?

**Comment by stevegreatrex** [comment]
See https://msdn.microsoft.com/en-gb/library/ff650316.aspx for an explanation

**Comment by floradu88** [comment]
I do agree with Steve, also this is a common practice in working with locks.

**Comment by swethapavan** [comment]
My bad thanks for explaining this.

**Comment by floradu88** [comment]
There is no bad idea, the purpose is to learn from each experience you go through.

**Pull request closed without merging**
